name: tugas_besar_pm2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  toastification: ^2.3.0
  fl_chart: ^0.68.0
  supabase_flutter: ^2.8.3
  mobile_scanner: ^6.0.6
  qr_flutter: ^4.1.0
  printing: ^5.11.0
  pdf: ^3.10.4
  scrollable_text_indicator: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/flutter.png
  - assets/logo.png
  - assets/user.png
  - assets/tech.jpg
  - assets/background.png
  - assets/inventory.png
